### ISSUE TITLE
Failed to build on arch

### ISSUE THREAD

**Issue by cjfloss** [NucleuxSoft/unitube-gtk#1]
```
[~/Code/rva]$ arch-meson unitube-gtk buildUni
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_lto=true -D b_pie=true unitube-gtk buildUni
The Meson build system
Version: 0.50.1
Source dir: /Files/Code/rva/unitube-gtk
Build dir: /Files/Code/rva/buildUni
Build type: native build
Project name: unitube-gtk
Project version: 0.1.0
Native C compiler: cc (gcc 8.3.0 "cc (GCC) 8.3.0")
Native Vala compiler: valac (valac 0.44.4)
Build machine cpu family: x86_64
Build machine cpu: x86_64

|Executing subproject vul 
|
|Project name: vul
|Project version: 0.3.0
|Native C compiler: cc (gcc 8.3.0 "cc (GCC) 8.3.0")
|Native Vala compiler: valac (valac 0.44.4)
|Found pkg-config: /usr/bin/pkg-config (1.6.1)
|Dependency gio-2.0 found: YES 2.60.3
|Dependency gee-0.8 found: YES 0.20.1
|Dependency libarchive found: YES 3.3.3
|Configuring gtext-1.0.deps using configuration
|Configuring gtext-1.0.pc using configuration
|Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
|Configuring gjson-1.0.deps using configuration
|Configuring gjson-1.0.pc using configuration
|Library m found: YES
|Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
|Configuring gcl-1.0.deps using configuration
|Configuring gcl-1.0.pc using configuration
|Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
|Build targets in project: 6
|Subproject vul finished.

Dependency glib-2.0 found: YES 2.60.3
Dependency gobject-2.0 found: YES 2.60.3
Dependency gtk+-3.0 found: YES 3.24.8
Dependency gee-0.8 found: YES (cached)
Dependency libsoup-2.4 found: YES 2.66.2
Dependency libhandy-0.0 found: YES 0.0.9
Configuring com.nucleuxsoft.UniTube.desktop.in using configuration
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program build-aux/post_install.py found: YES (/usr/bin/env python3 /Files/Code/rva/unitube-gtk/build-aux/post_install.py)
Build targets in project: 10
Found ninja-1.9.0 at /usr/bin/ninja
[~/Code/rva]$ ninja -C buildUni 
ninja: Entering directory `buildUni'
[3/68] Compiling Vala source ../unitube-gtk/subprojects/vu...ding.vala ../unitube-gtk/subprojects/vul/text/Writer.vala.
../unitube-gtk/subprojects/vul/text/Writer.vala:25.5-25.13: warning: unhandled error `GLib.Error'
				write (u);
				^^^^^^^^^
../unitube-gtk/subprojects/vul/text/Writer.vala:34.5-34.22: warning: unhandled error `GLib.Error'
				write_string (str);
				^^^^^^^^^^^^^^^^^^

(valac:14353): vala-CRITICAL **: 00:40:31.161: vala_struct_value_type_construct: assertion 'type_symbol != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.205: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.205: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.205: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.206: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.206: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.206: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.207: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.207: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.207: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.207: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.207: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.207: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.208: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.208: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.208: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.208: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.208: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.208: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.249: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.249: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.249: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.249: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.249: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.249: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.250: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.250: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.250: vala_ccode_function_add_parameter: assertion 'param != NULL' failed

(valac:14353): vala-ccodegen-CRITICAL **: 00:40:31.250: vala_get_ccode_name: assertion 'node != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.250: vala_ccode_parameter_construct: assertion 'type != NULL' failed

(valac:14353): vala-ccode-CRITICAL **: 00:40:31.250: vala_ccode_function_add_parameter: assertion 'param != NULL' failed
Compilation succeeded - 2 warning(s)
[4/68] Compiling Vala source ../unitube-gtk/subprojects/vu...ries.vala ../unitube-gtk/subprojects/vul/gcl/Archive.vala.
../unitube-gtk/subprojects/vul/gcl/Entry.vala:110.5-110.37: warning: unhandled error `GLib.Error'
				tmp_stream.seek (0, SeekType.END);
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../unitube-gtk/subprojects/vul/gcl/Entry.vala:112.5-112.39: warning: unhandled error `GLib.Error'
				tmp_stream.seek (pos, SeekType.SET);
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../unitube-gtk/subprojects/vul/gcl/Entry.vala:101.15-101.49: warning: unhandled error `GLib.Error'
			tmp_file = File.new_tmp (null, out tmp_stream);
			           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../unitube-gtk/subprojects/vul/gcl/Entries.vala:67.5-67.15: warning: `null' incompatible with return type `Gcl.Entry'
				return null;
				^^^^^^^^^^^
../unitube-gtk/subprojects/vul/gcl/Archive.vala:90.70-90.85: warning: use of possibly unassigned parameter `buffer'
		static ssize_t read_callback (LibArchive.Archive arch, void* data, out void* buffer) {
		                                                                   ^^^^^^^^^^^^^^^^
Compilation succeeded - 5 warning(s)
[5/68] Compiling C object 'subprojects/vul/text/0b1e80e@@gtext-1.0@sha/meson-generated_Reader.c.o'.
FAILED: subprojects/vul/text/0b1e80e@@gtext-1.0@sha/meson-generated_Reader.c.o 
cc -Isubprojects/vul/text/0b1e80e@@gtext-1.0@sha -Isubprojects/vul/text -I../unitube-gtk/subprojects/vul/text -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/gee-0.8 -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -fPIC -pthread -MD -MQ 'subprojects/vul/text/0b1e80e@@gtext-1.0@sha/meson-generated_Reader.c.o' -MF 'subprojects/vul/text/0b1e80e@@gtext-1.0@sha/meson-generated_Reader.c.o.d' -o 'subprojects/vul/text/0b1e80e@@gtext-1.0@sha/meson-generated_Reader.c.o' -c 'subprojects/vul/text/0b1e80e@@gtext-1.0@sha/Reader.c'
Reader.c: In function ‘_gtext_reader_read_async_co_gsource_func’:
Reader.c:616:39: error: ‘self’ undeclared (first use in this function)
Reader.c:616:39: note: each undeclared identifier is reported only once for each function it appears in
Reader.c: In function ‘___lambda4__gthread_func’:
Reader.c:644:45: error: ‘self’ undeclared (first use in this function)
Reader.c: In function ‘_gtext_reader_read_line_async_co_gsource_func’:
Reader.c:814:44: error: ‘self’ undeclared (first use in this function)
Reader.c: In function ‘___lambda5__gthread_func’:
Reader.c:847:45: error: ‘self’ undeclared (first use in this function)
Reader.c: In function ‘_gtext_reader_read_to_end_async_co_gsource_func’:
Reader.c:1011:46: error: ‘self’ undeclared (first use in this function)
Reader.c: In function ‘___lambda6__gthread_func’:
Reader.c:1044:45: error: ‘self’ undeclared (first use in this function)
[9/68] Generating com.nucleuxsoft.UniTube.desktop_data_merge with a custom command.
msgfmt: /Files/Code/rva/unitube-gtk/po/LINGUAS does not exist
[10/68] Compiling C object 'subprojects/vul/text/0b1e80e@@gtext-1.0@sha/meson-generated_StreamWriter.c.o'.
ninja: build stopped: subcommand failed.

```

**Comment by nahuelwexd** [comment]
Yeah, it happens 'cause VUL (Vale Utilities Library) doesn't build with Vala since Vala 0.44. I think is Vala-side issue, but I've not reported yet.
Downgrade to Vala 0.42 in order to build this project. Oh, and this project is WIP, but I didn't have enough time to work on it

**Comment by nahuelwexd** [comment]
Fixed in e02e9fc36aca2a74590547cc64b52b11af4ee0c4
